use_frameworks!

platform :ios, '9.0'

target 'TWImageBrower_Example' do
  pod 'TWImageBrower', :path => '../'
  
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  

  target 'TWImageBrower_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
